Firebase App Check initialized with reCAPTCHA Enterprise. PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: null, type: "unhandledrejection", target: Window…}
params are being enumerated. `params` should be unwrapped with `React.use()` before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.children`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

The keys of `searchParams` were accessed directly. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `Reflect.has(searchParams, "monospaceUid")`, `"monospaceUid" in searchParams`, or similar. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.monospaceUid`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: null, type: "unhandledrejection", target: Window…}

params are being enumerated. `params` should be unwrapped with `React.use()` before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.children`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

The keys of `searchParams` were accessed directly. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `Reflect.has(searchParams, "monospaceUid")`, `"monospaceUid" in searchParams`, or similar. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.monospaceUid`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

NotAllowedError: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.

PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: null, type: "unhandledrejection", target: Window…}

params are being enumerated. `params` should be unwrapped with `React.use()` before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.children`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

The keys of `searchParams` were accessed directly. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `Reflect.has(searchParams, "monospaceUid")`, `"monospaceUid" in searchParams`, or similar. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

A searchParam property was accessed directly with `searchParams.monospaceUid`. `searchParams` should be unwrapped with `React.use()` before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis

NotAllowedError: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.